### ISSUE TITLE
🐛 Bug Report — Runtime APIs Duplex Stream Not Pressent A:[Its not standard ;]

### ISSUE THREAD

**Issue by syonfox** [cloudflare/workerd#1293]
Hello, im wondering if there is a reson Duplex stream are not included. are they not standard? 

... https://stackoverflow.com/questions/74136196/why-does-web-streams-api-lack-duplex-stream

I guess not but might be nice to include anyway

```shell

07:34:58.937 | Error: Failed to publish your Function. Got error: Uncaught ReferenceError: 
Duplex is not defined   at functionsWorker-0.7853361025329599.js:368:18 in lib/cf-stream-
chain.js   at functionsWorker-0.7853361025329599.js:18:50 in __require2   at functionsWorker-
0.7853361025329599.js:480:38 in dump/steamChain.js   at functionsWorker-
0.7853361025329599.js:15:56 in __init   at functionsWorker-0.7853361025329599.js:554:5 in 
../../../../tmp/functionsRoutes-0.47306167156205037.mjs   at functionsWorker-
0.7853361025329599.js:15:56 in __init   at functionsWorker-0.7853361025329599.js:583:1

```

**Comment by syonfox** [comment]
https://github.com/nodejs/readable-stream/blob/268229d67620d092ea4d64de5416f55997eadbaa/lib/internal/streams/duplex.js#L48

**Comment by jasnell** [comment]
Duplex is a node.js API. Enable nodejs_compat compatibility flag to use it.
