### ISSUE TITLE
🐛 BUG: Uncaught exception

### ISSUE THREAD

**Issue by eloff** [cloudflare/workerd#1401]
### Which Cloudflare product(s) does this pertain to?

Wrangler or miniflare

### What version(s) of the tool(s) are you using?

3.5.0

### What version of Node are you using?

18.16.1

### What operating system are you using?

Linux (Ubuntu 20.04)

### Describe the Bug

In one of my handlers, after executing a select query with batch, I get the following exception: 

```workerd/server/server.c++:2533: error: Uncaught exception: kj/async-io-unix.c++:186: disconnected: remote.worker_do_not_log; Request failed due to internal error```

It seems it's in some kind of destructor or finalizer or other thread / cleanup task, since execution continues after the query, because I can see console.log output from subsequent code. However, the server crashes before it is able to return the response (client doesn't get a response back.) I can reproduce this every single run. Commenting out that query makes the exception go away. No other queries are executed in that request.

I deleted, the database, deleted .wrangler dir, and recreated the database. Same issue.

I created a new hello world project (following the getting started guide), containing only the "hello world" response and got the same exception *on the first run only*. Subsequent runs were fine. That's interesting, what state could wrangler be keeping that's the same for the machine, but not in the directory/project/code which all changed?

I switched back to the original project, reproduced the exception again. Went back to the new hello world, but it's fine now, I can't reproduce the exception in the hello world project again. Odd.

I then added the same database, same migrations, same query to the hello world project. No issues. I don't know how to make a minimal repro for it.

*edit*: I tried again this morning, after rebooting overnight. The error is gone, the reboot fixed it. It wasn't the query at fault here, probably not d1 (directly anyway). There's something else going on, and somehow a reboot fixed it.

It's tough to debug a problem with so little to go on. Is there anything I can do to get more info? Is there a way to build a debug version of wrangler or miniflare? Enable logging?

**Comment by penalosa** [comment]
I've transferred this to `workerd` since it looks like it's an error log coming from `workerd` rather than Wrangler directly

**Comment by jasnell** [comment]
We'll need a simple reproduction example in order to diagnose this.

**Comment by SyntaxColoring** [comment]
I'm not sure if this is exactly the same thing:

```
workerd/server/server.c++:3069: error: Uncaught exception: kj/compat/http.c++:3939: disconnected: worker_do_not_log; Request failed due to internal error
```

(Note ` kj/compat/http.c++:3939` instead of ` kj/async-io-unix.c++:186`.)

@jasnell I can reproduce this, but sometimes it requires patience.

1. Clone https://github.com/SyntaxColoring/cloudflare-crash-repro.
2. `npm install && npm run dev`.
3. In something like Postman, open a bunch of concurrent WebSocket connections to `localhost:8787`. I opened a few to `localhost:8787` and a few to `localhost:8787/some/other/path`.
4. Send a few messages on each connection.
5. Wait a few minutes. The error will probably happen on its own. Some (but not necessarily all?) of the WebSocket connections will disconnect. If it doesn't happen after a few minutes, send some more WebSocket messages and wait some more.

Here are the associated log files from one reproduction.

[wrangler-2024-01-14_18-07-47_964.log](https://github.com/cloudflare/workerd/files/13932714/wrangler-2024-01-14_18-07-47_964.log)

**Comment by gaberogan** [comment]
I was able to reproduce this using a bare minimum worker template with fetch('https://example.com').

Strangely it seems to work fine with fetch('http://ip-api.com/json'), so I think it's an issue with SSL.

Here is the reproduction: https://github.com/cloudflare/workers-sdk/files/14214588/test-worker.zip

I am using worker-sdk 3.28.0 and macOS 13.5 and node.js 18, but I don't think this matters because I've experienced this reliably on both my windows and mac computers, with different sdk versions and different node.js versions

Last week I was not experiencing this and I have no idea why..

**Comment by gaberogan** [comment]
Can we please rename this issue to something more useful? Like "internal error" on fetch with HTTPS

cc @jasnell

**Comment by akainocode** [comment]
I would like to confirm this issue, but it seemed to resolve with a restart of my machine. 

I am currently using WSL2 though, that might have an affect on it but above people have mentioned that it happens regardless of OS.

**Comment by robmv** [comment]
> We'll need a simple reproduction example in order to diagnose this.

I am new to Cloudfare Workers, so I am starting the Rust example project, so I think I have the simplest reproduction: 

1. Install the Rust example `npx wrangler generate hello-world-rust https://github.com/cloudflare/workers-sdk/templates/experimental/worker-rust`
2. Run `npx wrangler dev`
3. Open the example on the browser with `[b]` option.
4. When you get the `Hello, World!` output, just press Control+R to reload the browser without releasing the keys in order to reload indefinitely.

The same error presented here, with different line number, maybe it isn ´t the same case but I find it weird that a fast and simple REST endpoint like this could fail so easily.

```
 [ERROR] workerd/server/server.c++:3340: error: Uncaught exception: kj/async-io-unix.c++:778: disconnected: remote.worker_do_not_log; Request failed due to internal error`
```

**Comment by KyGuy2002** [comment]
I am using playwright testing in github actions and this error is spammed.  Doesn't seem to affect the behaviour of the server or success of the tests though, so not a huge deal for me.   This also happens when running the tests locally but doesnt happen when running the dev server and using the app normally.

**Comment by martian0x80** [comment]
Any updates on this? I keep getting similar errors:
```
✘ [ERROR] workerd/server/server.c++:3346: error: Uncaught exception: kj/async-io-unix.c++:778: disconnected: remote.worker_do_not_log; Request failed due to internal error

  stack:
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57e2823
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57e0c8d
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@412a4a4
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57ab0c0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57bf540
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57bf540
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57bf540
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ddb010
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2de5310
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@411945b
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@41189a0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ddb010
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3509cf0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@350a124
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@338e460
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3847199
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2de5310
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@411945b
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@41189a0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ddb010
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3509cf0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@350a124
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579e353
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@338f8ef
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579f72f
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579ffe1
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57a63c4


[wrangler:inf] POST /search 200 OK (2468ms)
[wrangler:inf] POST /search 200 OK (657ms)
[wrangler:inf] POST /search 200 OK (658ms)
[wrangler:inf] GET /student/00111503019 200 OK (669ms)
[wrangler:inf] GET /student/00414901823 200 OK (662ms)
[wrangler:inf] GET /student/00255311623 200 OK (4714ms)
[wrangler:inf] GET /student/00417703523 200 OK (3483ms)
[wrangler:inf] GET /student/00512588822 200 OK (636ms)
[wrangler:inf] GET /student/00255311623 200 OK (651ms)
[wrangler:inf] GET /student/00413215723 200 OK (5846ms)
✘ [ERROR] workerd/jsg/util.c++:251: error: e = kj/async-io-unix.c++:1298: failed: DNS lookup failed.; params.host = internal_suspense_cache_hostname.local; params.service = ; gai_strerror(status) = Name or service not known

  stack:
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57da5cc
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57dafe0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3fb3790
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@410b810
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@410d290
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@410d9f0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4121040
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@33d9546
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2de5310
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@357f4f0
  /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@35797f0;
  sentryErrorContext = jsgInternalError
  ```
  
  I am running `npx wrangler pages dev .vercel/output/static` after building the site with `npx @cloudflare/next-on-pages@latest`. Doesn't work locally or in prod (cf pages) either.

**Comment by HiraiKyo** [comment]
> Any updates on this? I keep getting similar errors:
> 
> ```
> ✘ [ERROR] workerd/server/server.c++:3346: error: Uncaught exception: kj/async-io-unix.c++:778: disconnected: remote.worker_do_not_log; Request failed due to internal error
> 
>   stack:
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57e2823
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57e0c8d
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@412a4a4
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57ab0c0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57bf540
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57bf540
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57bf540
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ddb010
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2de5310
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@411945b
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@41189a0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ddb010
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3509cf0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@350a124
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@338e460
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3847199
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2de5310
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@411945b
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@41189a0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2ddb010
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3509cf0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@350a124
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579e353
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@338f8ef
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579deef
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579f72f
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@579ffe1
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57a63c4
> 
> 
> [wrangler:inf] POST /search 200 OK (2468ms)
> [wrangler:inf] POST /search 200 OK (657ms)
> [wrangler:inf] POST /search 200 OK (658ms)
> [wrangler:inf] GET /student/00111503019 200 OK (669ms)
> [wrangler:inf] GET /student/00414901823 200 OK (662ms)
> [wrangler:inf] GET /student/00255311623 200 OK (4714ms)
> [wrangler:inf] GET /student/00417703523 200 OK (3483ms)
> [wrangler:inf] GET /student/00512588822 200 OK (636ms)
> [wrangler:inf] GET /student/00255311623 200 OK (651ms)
> [wrangler:inf] GET /student/00413215723 200 OK (5846ms)
> ✘ [ERROR] workerd/jsg/util.c++:251: error: e = kj/async-io-unix.c++:1298: failed: DNS lookup failed.; params.host = internal_suspense_cache_hostname.local; params.service = ; gai_strerror(status) = Name or service not known
> 
>   stack:
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57da5cc
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@57dafe0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3fb3790
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@410b810
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@410d290
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@410d9f0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4121040
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@33d9546
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2de5310
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@357f4f0
>   /home/martian/.npm/_npx/32026684e21afda6/node_modules/@cloudflare/workerd-linux-64/bin/workerd@35797f0;
>   sentryErrorContext = jsgInternalError
> ```
> 
> I am running `npx wrangler pages dev .vercel/output/static` after building the site with `npx @cloudflare/next-on-pages@latest`. Doesn't work locally or in prod (cf pages) either.

I had the exactly same error with minimal reproduction, based on this tutorial, with Ngrok hosting.
https://developers.cloudflare.com/durable-objects/examples/websocket-hibernation-server/

WebSocket handshaking is succeeded, but in a few minutes, connection got lost because of this above error.
This error does not appear when I just connect to localhost server. It is only on Ngrok environment.

Any solution?

**Comment by martian0x80** [comment]
> Any solution?

@HiraiKyo

None that I am aware of sorry, plus this issue seems old, I doubt we are getting any response or solution anytime soon.

**Comment by kentonv** [comment]
Any time you see "internal error", there should be a separate log line actually logging the real error. You need to look for that log line.

@martian0x80 in your example the actual error seems to be:

> failed: DNS lookup failed.; params.host = internal_suspense_cache_hostname.local; params.service = ; gai_strerror(status) = Name or service not known

This seems to be a regular DNS lookup error, probably specific to your environment.

Obviously the way these errors reported is not so great. Sorry about that. workerd's error logging is awkward since the code was originally designed to log errors that we, the Cloudflare Workers team, needed to address, while explicitly not logging problems that the application should address (those are simply delivered to the application as thrown exceptions). We really need to go back and come up with a better story here.

**Comment by HiraiKyo** [comment]
@kentonv Thanks mate, so I cannot get some meaningful log for websocket close :(

**Comment by martian0x80** [comment]
> Any time you see "internal error", there should be a separate log line actually logging the real error. You need to look for that log line.
> 
> @martian0x80 in your example the actual error seems to be:
> 
> > failed: DNS lookup failed.; params.host = internal_suspense_cache_hostname.local; params.service = ; gai_strerror(status) = Name or service not known
> 
> This seems to be a regular DNS lookup error, probably specific to your environment.
> 
> Obviously the way these errors reported is not so great. Sorry about that. workerd's error logging is awkward since the code was originally designed to log errors that we, the Cloudflare Workers team, needed to address, while explicitly not logging problems that the application should address (those are simply delivered to the application as thrown exceptions). We really need to go back and come up with a better story here.

Thanks for the response, I just tested it on a new Github Codespace as well and I get the same errors, even on the Cloudflare Pages deployment, which throws a silent "error code: 1016" in the logs, this is what wrangler logs say:

```
Connected to deployment <deployment-id>, waiting for logs...
GET https://xxxx.pages.dev/ - Ok @ 16/6/2024, 1:19:20 pm
  (error) error code: 1016
GET https://xxxx.pages.dev/favicon.ico - Ok @ 16/6/2024, 1:19:22 pm
GET https://xxxx.pages.dev/student/08215602721?_rsc=1rft4 - Ok @ 16/6/2024, 1:19:31 pm
  (error) error code: 1016
  (error) error code: 1016
```
This only occurs on pages that are server side rendered. I have no idea why 'internal_suspense_cache_hostname.local' is not resolved.
These are the errors, I have seen so far in the same log (ordered):
- `✘ [ERROR] workerd/jsg/util.c++:278: error: e = kj/async-io-unix.c++:1298: failed: DNS lookup failed.; params.host = internal_suspense_cache_hostname.local; params.service = ; gai_strerror(status) = Name or service not known`
- `✘ [ERROR] Uncaught (async) Error: internal error`
- `✘ [ERROR] A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's I/O context have already finished.`
- `✘ [ERROR] Uncaught (in response) Error: The script will never generate a response.`
- `✘ [ERROR] workerd/server/server.c++:3346: error: Uncaught exception: workerd/io/io-context.c++:1167: failed: remote.jsg.Error: The script will never generate a response.`

I wish I could debug this.

**Comment by dsmmcken** [comment]
I am seeing similar `(error) error code: 1016` in my logs. I am fetching a file from r2 with a regular fetch via a cloudflare configured custom domain. All of the DNS settings were setup with cloudflare. It's frustrating how little log information is available.

**Comment by kudlav** [comment]
Is there anything new on this? I have the same error. And there is just the internal error without any other _meaningful log_. `wrangler dev --remote`

```
✘ [ERROR] workerd/server/server.c++:3314: error: Uncaught exception: kj/async-io-unix.c++:778: disconnected: remote.worker_do_not_log; Request failed due to internal error

  stack: /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4fa3f63
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4fa23ad
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3a9b9f4
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6fab0
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f83180
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f83180
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f83180
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@27faf50
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2805070
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3a8b98b
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6313f
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3a8ae90
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@27faf50
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2f18c10
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2f19044
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6313f
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2da93e0
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@323e039
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2805070
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3a8b98b
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6313f
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3a8ae90
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@27faf50
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2f18c10
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2f19044
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6313f
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f634c3
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@2daa67f
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6313f
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6460c
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f64de1
  /home/vladan/dev/api-gate/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4f6b014
```

**Comment by troneras** [comment]
After removing .next , .vercel and .wrangler directories I was able to stop seeing this error. I had been without running the preview command for a while, so not sure what exactly caused the issue.

**Comment by jannisbecker** [comment]
> Is there anything new on this? I have the same error. And there is just the internal error without any other _meaningful log_. `wrangler dev --remote`
> 
> ```
> ✘ [ERROR] workerd/server/server.c++:3314: error: Uncaught exception: kj/async-io-unix.c++:778: disconnected: remote.worker_do_not_log; Request failed due to internal error
> 
>   stack: /home/vladan/dev/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4fa3f63
>   /home/vladan/dev/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4fa23ad
>   /home/vladan/dev/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3a9b9f4
> ```

I just had this issue and managed to resolve it by using 127.0.0.1 instead of localhost for wrangler.
For example by adding this to wrangler.toml

```
[dev]
ip = "127.0.0.1"
```

**Comment by erhathaway** [comment]
> > Is there anything new on this? I have the same error. And there is just the internal error without any other _meaningful log_. `wrangler dev --remote`
> > ```
> > ✘ [ERROR] workerd/server/server.c++:3314: error: Uncaught exception: kj/async-io-unix.c++:778: disconnected: remote.worker_do_not_log; Request failed due to internal error
> > 
> >   stack: /home/vladan/dev/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4fa3f63
> >   /home/vladan/dev/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4fa23ad
> >   /home/vladan/dev/node_modules/@cloudflare/workerd-linux-64/bin/workerd@3a9b9f4
> > ```
> 
> I just had this issue and managed to resolve it by using 127.0.0.1 instead of localhost for wrangler. For example by adding the following to wrangler.toml
> 
> ```
> [dev]
> ip = "127.0.0.1"
> ```
> 
> Seems to be some problem with DNS resolution.. which may explain why it worked for me on one machine and not the other..

Setting:

```
[dev]
ip = "127.0.0.1"
```

In wrangler.toml also worked for me! Thanks!

**Comment by kedom1337** [comment]
I also just ecountered seemingly the same error:
```txt
 This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not han
│ dled with .catch(). The promise rejected with the reason:
│ TypeError: Cannot read properties of undefined (reading 'toLowerCase')
│     at /home/kedom/Public/Git/viatro/node_modules/wrangler/wrangler-dist/cli.js:132318:25
│     at PassThrough.handler (/home/kedom/Public/Git/viatro/node_modules/wrangler/wrangler-dist/cli.js:132284:7)
│     at PassThrough.emit (node:events:519:28)
│     at PassThrough.emit (node:domain:488:12)
│     at emitKeys (node:internal/readline/utils:373:14)
│     at emitKeys.next (<anonymous>)
│     at PassThrough.onData (node:internal/readline/emitKeypressEvents:64:36)
│ ✘ [ERROR] workerd/server/server.c++:3613: error: Uncaught exception: kj/async-io-unix.c++:568: disconnected: ::read(fd, buffer, maxByte
│ s): Connection reset by peer
│ 
│   stack: /home/kedom/Public/Git/viatro/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5ae39c2
│   /home/kedom/Public/Git/viatro/node_modules/@cloudflare/workerd-linux-64/bin/workerd@5ae1925
│   /home/kedom/Public/Git/viatro/node_modules/@cloudflare/workerd-linux-64/bin/workerd@414b0ee
│   /home/kedom/Public/Git/viatro/node_modules/@cloudflare/workerd-linux-64/bin/workerd@41677e0
│   /home/kedom/Public/Git/viatro/node_modules/@cloudflare/workerd-linux-64/bin/workerd@41ac5ca
│   /home/kedom/Public/Git/viatro/node_modules/@cloudflare/workerd-linux-64/bin/workerd@4171f90
```

**Comment by godfat** [comment]
It's not fully clear if we're hitting into the same issue, but the error does look similar. Some context can be found at: https://gitlab.com/gitlab-org/gitlab/-/issues/499983#note_2262841638

4 weeks ago, the error looked like:

```
Uncaught exception: kj/async-io-unix.c++:186: disconnected: remote.worker_do_not_log; Request failed due to internal error
```

Now the error looked like:

```
workerd/server/server.c++:3898: error: Uncaught exception: kj/async-io-unix.c++:778: disconnected: remote.worker_do_not_log; Request failed due to internal error
```

This happened in our end-to-end tests. This is one of the jobs having this error: https://gitlab.com/gitlab-org/gitlab/-/jobs/8845758505

The log can be found in the artifacts (this will expire in a few days): https://gitlab.com/gitlab-org/gitlab/-/jobs/8845758505/artifacts/external_file/gdk.gitlab-http-router.log

**Comment by godfat** [comment]
If you're interested to try running the same end-to-end tests locally, here's the instructions:

* Set up a local GitLab instance via https://gitlab.com/gitlab-org/gitlab-development-kit
* You might need to set up an admin access token for the local GitLab instance, passing it via `GITLAB_QA_ADMIN_ACCESS_TOKEN` environment variable depending on the end-to-end tests you want to run (this error happened for all jobs running various tests)
* Change working directory to `gitlab-development-kit/gitlab/qa`
* Run a command like this `env 'GITLAB_QA_ADMIN_ACCESS_TOKEN'='-' bundle exec bin/qa Test::Instance::Blocking http://localhost:3000 -- --order random --force-color --format documentation qa/specs/features/browser_ui/4_verify/ci_variable/prefill_variables_spec.rb`
* Change `qa/specs/features/browser_ui/4_verify/ci_variable/prefill_variables_spec.rb` to any other end-to-end tests to run other end-to-end tests, such as `qa/specs/features/ee/browser_ui/3_create/merge_request/default_merge_request_template_spec.rb` and others as well.

**Comment by danlapid** [comment]
This was fixed in https://github.com/cloudflare/workerd/pull/3650 and https://github.com/cloudflare/workerd/pull/3816 
Let me know if this occurs again.

**Comment by veikkoeeva** [comment]
@danlapid Which versions the fixes landed? I can reliably produce

> [ERROR] workerd/io/worker-entrypoint.c++:365: error: e = kj/async-io-win32.c++:436: failed: WSASend(): #64 Määritetty verkkonimi ei ole enää käytettävissä.          
stack: 7ff63e786f6e 7ff63e76d63a 0 7ff63e8b84bf 7ff63e8b8ba8 0 0 0 0 0 0 7ff63e2f422e 7ff63e82d7bb 0 7ff63e7788ea 7ff63e8a3038 0 0 0; sentryErrorContext = workerEntrypoint                                                                                                                                                               

(Some Finnish mixed there, but looks like the same issue.)
