### ISSUE TITLE
🐛 BUG: Runtime API: cloudflare:sockets TypeError: Invalid URL: 1.1.1.1:1234

### ISSUE THREAD

**Issue by Ehco1996** [cloudflare/workerd#2232]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

3.59.0 [wrangler]

### What version of Node are you using?

v16.20.2

### What operating system and version are you using?

Mac

### Observed behavior

can not connet to ip:port

### Expected behavior

connect success

### Steps to reproduce
Please provide the following:
- A minimal working subset of your worker code

```JS
import { connect } from 'cloudflare:sockets';
async function handleRequest(request) {
	const tcpSocket = connect({ hostname: '1.1.1.1', port: 1234 });
	console.log(tcpSocket);
	return new Response("");
}

export default {
	async fetch(request, env, ctx) {
		return handleRequest(request);
	},
};

```
- A minimal working subset of your `wrangler.toml`
default one
- Commands used to start your local dev server, including custom env and cli args
defualt one

- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)
N/A

A git repo we can clone and run a test suit on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

```
.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-facade-1.js:14 TypeError: Invalid URL: 1.1.1.1:1234
    at connect (cloudflare:sockets:7:20)
    at handleRequest (index.js:4:21)
    at Object.fetch (index.js:13:12)
    at __facade_modules_fetch__ (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-loader.js:24:17)
    at __facade_invokeChain__ (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:16:10)
    at Object.next (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:13:14)
    at jsonError (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-facade-1.js:12:32)
    at __facade_invokeChain__ (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:16:10)
    at Object.next (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-common.js:13:14)
    at scheduled (.internal-fc0b03f8-5785-4f7b-a1f6-f7be1cb3bd5f-facade-0.js:9:24)
```

**Comment by jasnell** [comment]
hmm... looks like a regression. For the time being try turning on the `fetch_legacy_url` compatibility flag and see if that resolves it for you. Working on a fix now.

**Comment by Ehco1996** [comment]
`fetch_legacy_url` flag works , thanks for you support

**Comment by jasnell** [comment]
I believe the fix is going out in a release now. Maybe give things a test on monday to see if you can drop the flag.

**Comment by zizifn** [comment]
> I believe the fix is going out in a release now. Maybe give things a test on monday to see if you can drop the flag.

Thanks! connect to ip working fine now. But now seems `connect` method now will not throw any error even I input `hostname` as wrong ip or domain or worker itself hostname or port 25..

**Comment by dom96** [comment]
@zizifn was the error thrown before? Can you share your code?
