### ISSUE TITLE
🐛 BUG:Python dependency packages cannot be correctly imported on worker

### ISSUE THREAD

**Issue by freelixilong** [cloudflare/workerd#2279]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime

### What version(s) of the tool(s) are you using?

wrangler@3.60.3

### What version of Node are you using?

Python 3.10.12

### What operating system and version are you using?

Ubuntu 22.04

### Observed behavior
Python dependency packages cannot be correctly imported on worker, I want to imported requests package, but the requests depend on the urlib3, when i importing the failed happened. I had download the dependency package to the local.

Uncaught Error: PythonError: Traceback (most recent call last):
    File "/lib/python312.zip/_pyodide/_base.py", line 629, in pyimport_impl
      res = __import__(stem, fromlist=fromlist)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/session/metadata/entry.py", line 4, in <module>
      import requests
    File "/session/metadata/requests/__init__.py", line 43, in <module>
      import urllib3
    File "/session/metadata/urllib3/__init__.py", line 209, in <module>
      from .contrib.emscripten import inject_into_urllib3  # noqa: 401
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/session/metadata/urllib3/contrib/emscripten/__init__.py", line 6, in <module>
      from .connection import EmscriptenHTTPConnection, EmscriptenHTTPSConnection
    File "/session/metadata/urllib3/contrib/emscripten/connection.py", line 17, in <module>
      from .fetch import _RequestError, _TimeoutError, send_request, send_streaming_request
    File "/session/metadata/urllib3/contrib/emscripten/fetch.py", line 62, in <module>
      .read_text(encoding="utf-8")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/lib/python312.zip/pathlib.py", line 1027, in read_text
      with self.open(mode='r', encoding=encoding, errors=errors) as f:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/lib/python312.zip/pathlib.py", line 1013, in open
      return io.open(self, mode, buffering, encoding, errors, newline)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 44] No such file or directory:
  '/session/metadata/urllib3/contrib/emscripten/emscripten_fetch_worker.js'
  
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:9998) in new_error
    at [object Object] in $wrap_exception
    at [object Object] in $pythonexc2js
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:607956) in Module._pythonexc2js
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:64098) in
  Module.callPyObjectKwargs
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:65055) in Module.callPyObject
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:79132) in apply
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:77371) in apply
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:102862) in pyimport
    at null.<anonymous> (pyodide:python-entrypoint-helper:31:18) in pyimportMainModule
   [code: 10021]

### Expected behavior
npx wrangler deploy

### Steps to reproduce
The simple worker file

from js import Response

import requests
async def on_fetch(request, env):
    return Response.new("Hello world!")

### Please provide any relevant error logs

Uncaught Error: PythonError: Traceback (most recent call last):
    File "/lib/python312.zip/_pyodide/_base.py", line 629, in pyimport_impl
      res = __import__(stem, fromlist=fromlist)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/session/metadata/entry.py", line 4, in <module>
      import requests
    File "/session/metadata/requests/__init__.py", line 43, in <module>
      import urllib3
    File "/session/metadata/urllib3/__init__.py", line 209, in <module>
      from .contrib.emscripten import inject_into_urllib3  # noqa: 401
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/session/metadata/urllib3/contrib/emscripten/__init__.py", line 6, in <module>
      from .connection import EmscriptenHTTPConnection, EmscriptenHTTPSConnection
    File "/session/metadata/urllib3/contrib/emscripten/connection.py", line 17, in <module>
      from .fetch import _RequestError, _TimeoutError, send_request, send_streaming_request
    File "/session/metadata/urllib3/contrib/emscripten/fetch.py", line 62, in <module>
      .read_text(encoding="utf-8")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/lib/python312.zip/pathlib.py", line 1027, in read_text
      with self.open(mode='r', encoding=encoding, errors=errors) as f:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/lib/python312.zip/pathlib.py", line 1013, in open
      return io.open(self, mode, buffering, encoding, errors, newline)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 44] No such file or directory:
  '/session/metadata/urllib3/contrib/emscripten/emscripten_fetch_worker.js'
  
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:9998) in new_error
    at [object Object] in $wrap_exception
    at [object Object] in $pythonexc2js
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:607956) in Module._pythonexc2js
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:64098) in
  Module.callPyObjectKwargs
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:65055) in Module.callPyObject
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:79132) in apply
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:77371) in apply
    at null.<anonymous> (pyodide-internal:generated/pyodide.asm:20:102862) in pyimport
    at null.<anonymous> (pyodide:python-entrypoint-helper:31:18) in pyimportMainModule
   [code: 10021]

**Comment by dom96** [comment]
Can you share your worker's full directory?  Your Python script looks good, but are you also creating a requirements.txt file with `requests` in there?

**Comment by freelixilong** [comment]
> Can you share your worker's full directory structure (including the file's contents)? Your Python script looks good, but are you also creating a requirements.txt file with `requests` in there?

The tutorial informs me that, for the time being, it does not support installing all dependencies through requirements.txt, so I have packaged all the dependencies locally. It is almost an empty project. The requirements.txt is also empty.

**Comment by homerjam** [comment]
I'm also having this issue, I'm using pywrangler

```
# pyproject.toml

[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["langchain_core", "langchain_openai"]

[dependency-groups]
dev = ["workers-py"]

```
