### ISSUE TITLE
🐛 BUG: (macOS dev beta) `ERR_RUNTIME_FAILURE` error when using `wrangler dev`

### ISSUE THREAD

**Issue by Helloyunho** [cloudflare/workerd#2586]
FYI, I already made [a post in discord](https://discord.com/channels/595317990191398933/1261365846165688412/1261365846165688412) but no one was answering

### Which Cloudflare product(s) does this pertain to?

Wrangler

### What version(s) of the tool(s) are you using?

3.64.0 [Wrangler]

### What version of Node are you using?

22.0.0(now 22.4.1 since i upgraded it, but not fixed), but prefer bun 1.1.20

### What operating system and version are you using?

macOS Sequoia 15 dev beta 3

### Observed behavior
I get `ERR_RUNTIME_FAILURE` error when using `wrangler dev`
![CleanShot 2024-07-14 at 21 26 58@2x](https://github.com/user-attachments/assets/10053449-1bea-4a95-8272-1c631fb513b7)

### Expected behavior
Works without any error, ex) apply db, open dev server, etc.

### Steps to reproduce
- A minimal working subset of your worker code
```ts
import { Hono, type Context } from 'hono'
import { authHandler, initAuthConfig, type AuthConfig } from '@hono/auth-js'
import { PrismaAdapter } from '@auth/prisma-adapter'
import { PrismaClient } from '@prisma/client'
import { PrismaD1 } from '@prisma/adapter-d1'
import type { D1Database } from '@cloudflare/workers-types'
import users from './routes/users'

declare let env: {
  DB: D1Database
}

const app = new Hono()

const adapter = new PrismaD1(env.DB)
const prisma = new PrismaClient({ adapter })

function getAuthConfig(c: Context): AuthConfig {
  return {
    // auth config...
  }
}

app.use('*', initAuthConfig(getAuthConfig))
app.use('/api/auth/*', authHandler())
app.route('/api/users', users)

export default app

```
- A minimal working subset of your `wrangler.toml`
```toml
name = "[REDACTED]"
main = "api/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "[REDACTED]"
database_id = "[REDACTED]"
preview_database_id = "DB"
```
- Commands used to start your local dev server, including custom env and cli args
```sh
bunx wrangler dev # or npx wrangler dev, results are same
```
- Steps to be performed in the browser, curl commands, or a test we can run that reliably fails (at least a percent of the time)
  - use the command `wrangler dev`, that's it

A git repo we can clone and run a test suite on, or which has a README with step-by-step instructions, is even better. In this case, please use the field below to provide a link to the minimal repro.

### Please provide any relevant error logs

```
# when using wrangler dev


 ⛅️ wrangler 3.64.0
-------------------

Using vars defined in .dev.vars
Your worker has access to the following bindings:
- D1 Databases:
  - DB: [REDACTED] (DB), Preview: (DB)
- Vars:
  - GOOGLE_ID: "(hidden)"
  - GOOGLE_SECRET: "(hidden)"
  - AUTH_SECRET: "(hidden)"
  - TEBI_ACCESS_ID: "(hidden)"
  - TEBI_ACCESS_SECRET: "(hidden)"
⎔ Starting local server...
╭────────────────────────────────────────────╮
│ [ open a[d open D[ turn off [ clear  [ to  │
│ ]browser, vtools,]local mode]console,]exit │
│                                            │
╰────────────────────────────────────────────╯
/Users/helloyunho/Projects/[REDACTED]/node_modules/wrangler/wrangler-dist/cli.js:29765
            throw a;
            ^

MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/helloyunho/Projects/[REDACTED]/node_modules/miniflare/dist/src/index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (/Users/helloyunho/Projects/[REDACTED]/node_modules/miniflare/dist/src/index.js:3521:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}

Node.js v22.4.1
```

**Comment by ayonn985** [comment]
> Still persists on macOS 15 dev beta 6...

Hello brother, if you still have this issue on the Windows system, please refer to this link for a solution. I have already solved the problem of not being able to run `npm run dev` or `wrangler dev` using this method. If you also get a solution as a result, I will be very happy for you. We can become good friends.

link: https://github.com/cloudflare/workers-sdk/issues/6170#issuecomment-2239513454
summarize: Update To Microsoft Visual C++2015-2022 Redistributable (x64) -14.40.33810

**Comment by jasper283** [comment]
Hi, any updated? I have tried workerd@1.20240614.0 but still not working on macOS 15.2

**Comment by jasper283** [comment]
> [@jasper283](https://github.com/jasper283) can you provide more details of your setup? We use MacOS here and Wrangler has been working on 15.2 throughout (and now also on 15.3). The issue above appeared to be related to beta versions of the OS.

environment: 
- macOS Sequoia 15.3.1
- Node v22.14.0

package.json
```
{
	"name": "my-first-worker",
	"version": "0.0.0",
	"private": true,
	"scripts": {
		"deploy": "wrangler deploy",
		"dev": "wrangler dev",
		"start": "wrangler dev",
		"test": "vitest",
		"cf-typegen": "wrangler types"
	},
	"devDependencies": {
		"@cloudflare/vitest-pool-workers": "^0.6.4",
		"@cloudflare/workers-types": "^4.20250214.0",
		"typescript": "^5.5.2",
		"vitest": "~2.1.9",
		"wrangler": "^3.109.2"
	}
}
```

I successfully initialized a simple project by following the steps outlined in the [Cloudflare Workers documentation](https://developers.cloudflare.com/workers/get-started/guide/). After setting up the project with `pnpm create cloudflare@latest my-first-worker`, I attempted to start the development server using: `npx wrangler dev`. 
Here is the full execution log generated during the process:
```
--- 2025-02-19T03:04:59.030Z debug
🪵  Writing logs to "/Users/kim/.wrangler/logs/wrangler-2025-02-19_03-04-58_959.log"
---

--- 2025-02-19T03:04:59.030Z debug
Metrics dispatcher: Posting data {"deviceId":"c8cf8276-b78b-408e-88cf-ba1f6ac372bd","event":"wrangler command started","timestamp":1739934299030,"properties":{"amplitude_session_id":1739934299028,"amplitude_event_id":0,"wranglerVersion":"3.109.2","osPlatform":"Mac OS","osVersion":"Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:06 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T8103","nodeVersion":22,"packageManager":"pnpm","isFirstUsage":false,"configFileType":"jsonc","isCI":false,"isPagesCI":false,"isWorkersCI":false,"isInteractive":true,"hasAssets":false,"argsUsed":[],"argsCombination":"","command":"wrangler dev","args":{"xJsonConfig":true,"j":true,"latest":true,"noBundle":false,"remote":false,"r":false,"testScheduled":false,"xVectorizeBindToProd":false,"xImagesLocalMode":false}}}
---

--- 2025-02-19T03:04:59.034Z debug
.env file not found at ".env". Continuing... For more details, refer to https://developers.cloudflare.com/workers/wrangler/system-environment-variables/
---

--- 2025-02-19T03:04:59.059Z log

 ⛅️ wrangler 3.109.2
--------------------

---

--- 2025-02-19T03:04:59.077Z debug
.env file not found at ".dev.vars". Continuing... For more details, refer to https://developers.cloudflare.com/workers/wrangler/system-environment-variables/
---

--- 2025-02-19T03:04:59.077Z log
No bindings found.
---

--- 2025-02-19T03:04:59.104Z debug
RemoteRuntimeController teardown beginning...
---

--- 2025-02-19T03:04:59.105Z debug
RemoteRuntimeController teardown complete
---

--- 2025-02-19T03:04:59.105Z log
⎔ Starting local server...
---

--- 2025-02-19T03:04:59.217Z debug
*** Fatal uncaught kj::Exception: kj/async-io-unix.c++:945: failed: ::bind(sockfd, &addr.generic, addrlen): Invalid argument; toString() = [fe80::10]:8787
stack: 102f5b89f 102f5b69b 102f5a287 100a93f23 100a9480f 100a9508f 100a957df 100a3a6f7 102f82043 102f82353 102f80d3f 102f80ac3 100a28843 194868273
---

--- 2025-02-19T03:04:59.218Z debug
Error in ProxyController: Could not connect to InspectorProxyWorker
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:14362:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:1345:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---

--- 2025-02-19T03:04:59.219Z debug
=> Error contextual data: {
  config: {
    name: 'my-first-worker',
    config: '/Users/kim/Documents/Projects/nodejs/my-first-worker/wrangler.jsonc',
    compatibilityDate: '2025-02-14',
    compatibilityFlags: [],
    entrypoint: '/Users/kim/Documents/Projects/nodejs/my-first-worker/src/index.ts',
    projectRoot: '/Users/kim/Documents/Projects/nodejs/my-first-worker',
    bindings: {},
    migrations: [],
    sendMetrics: undefined,
    triggers: [],
    env: undefined,
    build: {
      alias: undefined,
      additionalModules: [],
      processEntrypoint: false,
      bundle: true,
      findAdditionalModules: undefined,
      moduleRoot: '/Users/kim/Documents/Projects/nodejs/my-first-worker/src',
      moduleRules: [],
      minify: undefined,
      define: {},
      custom: [Object],
      format: 'modules',
      nodejsCompatMode: null,
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      exports: [Array]
    },
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: '/Users/kim/Documents/Projects/nodejs/my-first-worker/.wrangler/state',
      registry: undefined,
      bindVectorizeToProd: false,
      multiworkerPrimary: undefined,
      imagesLocalMode: false
    },
    legacy: {
      site: undefined,
      legacyAssets: undefined,
      enableServiceEnvironments: false
    },
    unsafe: { capnp: undefined, metadata: undefined },
    assets: undefined
  },
  bundle: undefined
}
---

--- 2025-02-19T03:04:59.222Z debug
Error in ProxyController: Failed to start ProxyWorker or InspectorProxyWorker
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:14362:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:1345:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---

--- 2025-02-19T03:04:59.222Z debug
=> Error contextual data: {
  config: {
    name: 'my-first-worker',
    config: '/Users/kim/Documents/Projects/nodejs/my-first-worker/wrangler.jsonc',
    compatibilityDate: '2025-02-14',
    compatibilityFlags: [],
    entrypoint: '/Users/kim/Documents/Projects/nodejs/my-first-worker/src/index.ts',
    projectRoot: '/Users/kim/Documents/Projects/nodejs/my-first-worker',
    bindings: {},
    migrations: [],
    sendMetrics: undefined,
    triggers: [],
    env: undefined,
    build: {
      alias: undefined,
      additionalModules: [],
      processEntrypoint: false,
      bundle: true,
      findAdditionalModules: undefined,
      moduleRoot: '/Users/kim/Documents/Projects/nodejs/my-first-worker/src',
      moduleRules: [],
      minify: undefined,
      define: {},
      custom: [Object],
      format: 'modules',
      nodejsCompatMode: null,
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      exports: [Array]
    },
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: '/Users/kim/Documents/Projects/nodejs/my-first-worker/.wrangler/state',
      registry: undefined,
      bindVectorizeToProd: false,
      multiworkerPrimary: undefined,
      imagesLocalMode: false
    },
    legacy: {
      site: undefined,
      legacyAssets: undefined,
      enableServiceEnvironments: false
    },
    unsafe: { capnp: undefined, metadata: undefined },
    assets: undefined
  },
  bundle: undefined
}
---

--- 2025-02-19T03:04:59.222Z debug
Error in ProxyController: Failed to send message to InspectorProxyWorker: {"type":"reloadStart"}
 MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:14362:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:1345:16) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
---

--- 2025-02-19T03:04:59.222Z debug
=> Error contextual data: {
  config: {
    name: 'my-first-worker',
    config: '/Users/kim/Documents/Projects/nodejs/my-first-worker/wrangler.jsonc',
    compatibilityDate: '2025-02-14',
    compatibilityFlags: [],
    entrypoint: '/Users/kim/Documents/Projects/nodejs/my-first-worker/src/index.ts',
    projectRoot: '/Users/kim/Documents/Projects/nodejs/my-first-worker',
    bindings: {},
    migrations: [],
    sendMetrics: undefined,
    triggers: [],
    env: undefined,
    build: {
      alias: undefined,
      additionalModules: [],
      processEntrypoint: false,
      bundle: true,
      findAdditionalModules: undefined,
      moduleRoot: '/Users/kim/Documents/Projects/nodejs/my-first-worker/src',
      moduleRules: [],
      minify: undefined,
      define: {},
      custom: [Object],
      format: 'modules',
      nodejsCompatMode: null,
      jsxFactory: 'React.createElement',
      jsxFragment: 'React.Fragment',
      tsconfig: undefined,
      exports: [Array]
    },
    dev: {
      auth: [AsyncFunction: auth],
      remote: false,
      server: [Object],
      inspector: [Object],
      origin: [Object],
      liveReload: false,
      testScheduled: false,
      persist: '/Users/kim/Documents/Projects/nodejs/my-first-worker/.wrangler/state',
      registry: undefined,
      bindVectorizeToProd: false,
      multiworkerPrimary: undefined,
      imagesLocalMode: false
    },
    legacy: {
      site: undefined,
      legacyAssets: undefined,
      enableServiceEnvironments: false
    },
    unsafe: { capnp: undefined, metadata: undefined },
    assets: undefined
  },
  bundle: undefined
}
---

--- 2025-02-19T03:04:59.222Z log

---

--- 2025-02-19T03:04:59.244Z error
✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.


---

--- 2025-02-19T03:04:59.245Z debug
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:14362:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (/Users/kim/Documents/Projects/nodejs/my-first-worker/node_modules/.pnpm/miniflare@3.20250214.0/node_modules/miniflare/dist/src/index.js:1345:16)
---

--- 2025-02-19T03:04:59.245Z log
If you think this is a bug then please create an issue at https://github.com/cloudflare/workers-sdk/issues/new/choose
---

--- 2025-02-19T03:05:01.855Z debug
Sentry: Reporting disabled - would have sent MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above..
---

--- 2025-02-19T03:05:01.857Z debug
Metrics dispatcher: Posting data {"deviceId":"c8cf8276-b78b-408e-88cf-ba1f6ac372bd","event":"wrangler command errored","timestamp":1739934301857,"properties":{"amplitude_session_id":1739934299028,"amplitude_event_id":1,"wranglerVersion":"3.109.2","osPlatform":"Mac OS","osVersion":"Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:06 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T8103","nodeVersion":22,"packageManager":"pnpm","isFirstUsage":false,"configFileType":"jsonc","isCI":false,"isPagesCI":false,"isWorkersCI":false,"isInteractive":true,"hasAssets":false,"argsUsed":[],"argsCombination":"","command":"wrangler dev","args":{"xJsonConfig":true,"j":true,"latest":true,"noBundle":false,"remote":false,"r":false,"testScheduled":false,"xVectorizeBindToProd":false,"xImagesLocalMode":false},"durationMs":2836,"durationSeconds":2.836,"durationMinutes":0.047266666666666665}}
---
```

**Comment by RichardJohnn** [comment]
I too am seeing this "Could not connect to InspectorProxyWorker" running `wrangler dev` (3.109.2) and port 8787 is not in use

**Comment by RichardJohnn** [comment]
oh, I had `192.0.2.2       localhost` in my /etc/hosts 

working now 👍
