### ISSUE TITLE
`WeakRef` not supported in `workerd`

### ISSUE THREAD

**Issue by marzcreatives** [cloudflare/workerd#3053]
### Which Cloudflare product(s) does this pertain to?

Workers Runtime, Wrangler

### What version(s) of the tool(s) are you using?

3.84.1 [Wrangler]

### What version of Node are you using?

20

### What operating system and version are you using?

Mac Sequoia

### Describe the Bug

It should build and deploy to CloudFlare but it keeps erring saying WeakRef is not supported. 
But WeakRef is being used by discord.js dependency in node_modules so there isn't anything I can do.
What's a work around?

package.json
```
{
  "name": "tqihelperbot",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "wrangler dev",
    "deploy": "wrangler deploy"
  },
  "dependencies": {
    "discord-interactions": "^4.1.0",
    "discord.js": "^14.16.3",
    "wrangler": "^3.84.1"
  },
  "packageManager": "yarn@4.5.0",
  "devDependencies": {
    "buffer": "^6.0.3"
  }
}
```

wrangler.toml
```
main = "src/index.js"

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-10-04"
```

### Please provide a link to a minimal reproduction

https://github.com/marzcreatives/tqiHelperBot

### Please provide any relevant error logs

 ⛅️ wrangler 3.84.1
-------------------

[wrangler:inf] Ready on http://localhost:8787
⎔ Starting local server...
✘ [ERROR] service core:user:tqihelperbot: Uncaught ReferenceError: WeakRef is not defined

    at null.<anonymous> (index.js:33089:16) in module2.exports
    at null.<anonymous> (index.js:33107:87) in node_modules/undici/lib/web/fetch/request.js
    at null.<anonymous> (index.js:30:50) in __require2
    at null.<anonymous> (index.js:33820:47) in node_modules/undici/lib/web/fetch/index.js
    at null.<anonymous> (index.js:30:50) in __require2
    at null.<anonymous> (index.js:39554:21) in node_modules/undici/index.js
    at null.<anonymous> (index.js:30:50) in __require2
    at null.<anonymous> (index.js:42327:29) in node_modules/discord.js/src/util/Util.js
    at null.<anonymous> (index.js:30:50) in __require2
    at null.<anonymous> (index.js:42648:23) in node_modules/discord.js/src/client/BaseClient.js

✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.

**Comment by jasnell** [comment]
I'll mark this as a feature request. Workers intentionally disables use of `WeakRef` and `FinalizationRegistry` in order to limit observability of GC, and the nondeterminism it brings, for a number of reasons. I believe `WeakRef` would likely be somewhat safer to enable than `FinalizationRegistry` but they are used so frequently together that it might actually cause more issues to enable one but not the other. We'll need to carefully consider this.

**Comment by deanilvincent** [comment]
Hi, same issue when using elasticsearch.js 

<img width="549" alt="image" src="https://github.com/user-attachments/assets/89f696f3-6f9e-4f7d-8c74-b5ab4a6f34dd" />

Any quick solution for now?

**Comment by marcoaleixo** [comment]
hey - did you find any way to bypass this?

**Comment by jasnell** [comment]
There is currently no workaround for this. We completely disable the ability for `WeakRef` and `FinalizationRegistry` to work in the runtime and make those completely unavailable. We have been exploring whether there is a path to re-enabling it but for now these will not work and there is no workaround.

**Comment by ketanhwr** [comment]
This is now [supported](https://developers.cloudflare.com/changelog/2025-05-08-finalization-registry/). See #3560
