### ISSUE TITLE
Error when installing packages

### ISSUE THREAD

**Issue by oo00spy00oo** [cloudflare/workerd#320]
# Info
```
pnpm: 7
node: 18
wrangler 2.8.1 
OS: Alpine Linux
```

# Command: 
```
apk add --no-cache libc6-compat gcompat libunwind
pnpm install
```

# Error
```
.../node_modules/better-sqlite3 install$ prebuild-install || node-gyp rebuild --release
.../node_modules/@parcel/watcher install$ node-gyp-build
.../node_modules/@parcel/watcher install: Done
.../node_modules/better-sqlite3 install: Done
.../node_modules/@swc/core postinstall$ node postinstall.js
.../esbuild@0.14.51/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.16.17/node_modules/esbuild postinstall$ node install.js
.../node_modules/workerd postinstall$ node install.js
.../node_modules/@swc/core postinstall: Done
.../esbuild@0.14.51/node_modules/esbuild postinstall: Done
.../esbuild@0.16.17/node_modules/esbuild postinstall: Done
.../node_modules/workerd postinstall: node:internal/errors:491
.../node_modules/workerd postinstall:     ErrorCaptureStackTrace(err);
.../node_modules/workerd postinstall:     ^
.../node_modules/workerd postinstall: <ref *1> Error: spawnSync /builds/project/project-worker/node_modules/.pnpm/workerd@1.20230115.0/node_modules/workerd/bin/workerd ENOBUFS
.../node_modules/workerd postinstall:     at Object.spawnSync (node:internal/child_process:1110:20)
.../node_modules/workerd postinstall:     at spawnSync (node:child_process:871:24)
.../node_modules/workerd postinstall:     at Object.execFileSync (node:child_process:914:15)
.../node_modules/workerd postinstall:     at validateBinaryVersion (/builds/project/project-worker/node_modules/.pnpm/workerd@1.20230115.0/node_modules/workerd/install.js:61:47)
.../node_modules/workerd postinstall:     at /builds/project/project-worker/node_modules/.pnpm/workerd@1.20230115.0/node_modules/workerd/install.js:230:7 {
.../node_modules/workerd postinstall:   errno: -105,
.../node_modules/workerd postinstall:   code: 'ENOBUFS',
.../node_modules/workerd postinstall:   syscall: 'spawnSync /builds/project/project-worker/node_modules/.pnpm/workerd@1.20230115.0/node_modules/workerd/bin/workerd',
.../node_modules/workerd postinstall:   path: '/builds/project/project-worker/node_modules/.pnpm/workerd@1.20230115.0/node_modules/workerd/bin/workerd',
.../node_modules/workerd postinstall:   spawnargs: [ '--version' ],
.../node_modules/workerd postinstall:   error: [Circular *1],
.../node_modules/workerd postinstall:   status: null,
.../node_modules/workerd postinstall:   signal: 'SIGTERM',
.../node_modules/workerd postinstall:   output: [
.../node_modules/workerd postinstall:     null,
.../node_modules/workerd postinstall:     Buffer(0) [Uint8Array] [],
.../node_modules/workerd postinstall:     Buffer(1048675) [Uint8Array] [
.../node_modules/workerd postinstall:        69, 114, 114, 111, 114,  32, 108, 111,  97, 100, 105, 110,
.../node_modules/workerd postinstall:       103,  32, 115, 104,  97, 114, 101, 100,  32, 108, 105,  98,
.../node_modules/workerd postinstall:       114,  97, 114, 121,  32, 108, 105,  98,  99,  43,  43,  46,
.../node_modules/workerd postinstall:       115, 111,  46,  49,  58,  32,  78, 111,  32, 115, 117,  99,
.../node_modules/workerd postinstall:       104,  32, 102, 105, 108, 101,  32, 111, 114,  32, 100, 105,
.../node_modules/workerd postinstall:       114, 101,  99, 116, 111, 114, 121,  32,  40, 110, 101, 101,
.../node_modules/workerd postinstall:       100, 101, 100,  32,  98, 121,  32,  47,  98, 117, 105, 108,
.../node_modules/workerd postinstall:       100, 115,  47, 112, 111, 111, 108,  97, 114, 109, 121,  47,
.../node_modules/workerd postinstall:       112, 111, 111, 108,
.../node_modules/workerd postinstall:       ... 1048575 more items
.../node_modules/workerd postinstall:     ]
.../node_modules/workerd postinstall:   ],
.../node_modules/workerd postinstall:   pid: 103,
.../node_modules/workerd postinstall:   stdout: Buffer(0) [Uint8Array] [],
.../node_modules/workerd postinstall:   stderr: Buffer(1048675) [Uint8Array] [
.../node_modules/workerd postinstall:      69, 114, 114, 111, 114,  32, 108, 111,  97, 100, 105, 110,
.../node_modules/workerd postinstall:     103,  32, 115, 104,  97, 114, 101, 100,  32, 108, 105,  98,
.../node_modules/workerd postinstall:     114,  97, 114, 121,  32, 108, 105,  98,  99,  43,  43,  46,
.../node_modules/workerd postinstall:     115, 111,  46,  49,  58,  32,  78, 111,  32, 115, 117,  99,
.../node_modules/workerd postinstall:     104,  32, 102, 105, 108, 101,  32, 111, 114,  32, 100, 105,
.../node_modules/workerd postinstall:     114, 101,  99, 116, 111, 114, 121,  32,  40, 110, 101, 101,
.../node_modules/workerd postinstall:     100, 101, 100,  32,  98, 121,  32,  47,  98, 117, 105, 108,
.../node_modules/workerd postinstall:     100, 115,  47, 112, 111, 111, 108,  97, 114, 109, 121,  47,
.../node_modules/workerd postinstall:     112, 111, 111, 108,
.../node_modules/workerd postinstall:     ... 1048575 more items
.../node_modules/workerd postinstall:   ]
.../node_modules/workerd postinstall: }
.../node_modules/workerd postinstall: Node.js v18.13.0
.../node_modules/workerd postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by kentonv** [comment]
Hi @oo00spy00oo,

The `ENOBUFS` error code suggests the machine may have run out of RAM. How much RAM do you have?

That said, in #286 it was also observed that Alpine Linux does not have packages for `libc++`, which is a required dependency of `workerd`. So it might be hard to get this running on Alpine.
