### ISSUE TITLE
Question about streams

### ISSUE THREAD

**Issue by vicb** [cloudflare/workerd#3245]
ref issue: https://github.com/cloudflare/workerd/issues/2746

^ this issue is about workerd streams not compatible with Node stream. The reason is that we want to stick to the specs while Node (/undici) does not.

In workerd, it is not possible to initialize the body with a `Readable` as in:

```
const req = new Request('http://example.com', { method: 'POST', body: readable });
```

We have used [a workaround for NextJS](https://github.com/opennextjs/opennextjs-cloudflare/blob/021ddb7ef630e0162b9fb55226b82ce6bfd13efc/packages/cloudflare/src/cli/build/build-worker.ts#L129): `{ body: Readable.toWeb(readable) }`

The workaround stopped working following some updates in the Next adapter code base.

There is a repro in https://github.com/vicb/workerd-stream

- checkout the code
- `npm i`
- `npx wrangler dev`
- hit b in the console to send a request (or use `curl`)

You will see the following error:

```
[wrangler:err] ReferenceError: decoder is not defined
    at Object.fetch (file:///Users/vberchet/code/work/extends-readable/src/index.ts:88:16)
    at async jsonError (file:///Users/vberchet/code/work/extends-readable/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
    at async drainBody (file:///Users/vberchet/code/work/extends-readable/node_modules/wrangler/templates/middleware/middleware-ensure-req-body-drained.ts:5:10)
```

It originates in:

```ts
		// Error with:
		// TypeError: This ReadableStream is disturbed (has already been read from), and cannot be used as a body.
		const req = new Request('http://example.com', { method: 'POST', body: Readable.toWeb(ic) });

		// Works
		//const req = new Request('http://example.com', { method: 'POST', body: ReadableStream.from(ic) });
```

You can see that the first snippet that used to work now error.

ic is an instance of `IncomingMessage` (local)  < `http.IncomingMessage` (unenv) < `Readable` (workerd)

Note that before https://github.com/unjs/unenv/pull/363 (2w ago), the `Readable` implementation was coming from `unenv`. It might explain why this code used to work.

Still I think `{ body: Readable.toWeb(ic) }` should work and we should understand why it doesn't.

Other info:

I have tried to call `Readable.isDisturbed(ic)` right before the super constructor call and it returns `false`.

@jasnell could you please help investigate?

**Comment by jasnell** [comment]
Will investigate... likely will need to be next week tho at the earliest.

**Comment by vicb** [comment]
Thanks @jasnell 
No rush on this one as we have a workaround but I think we should figure out what's going on here.

**Comment by vicb** [comment]
Tested with a compatibility date set to `2026-01-01` and flags set to `["nodejs_compat"]` to validate that this now WAI.
